### PR TITLE
Add MogDB schema

### PR DESCRIPTION
**Pull request by travelliu**
add mogdb schema. www.mogdb.io

### CODE REVIEW

**Comment by kenshaw** [comment]
The driver you've added here just seems to be a fork of the regular `lib/pq` driver. We already have 2 PostgreSQL drivers. I see no need to add another. If you'd like to add a driver alias to the `lib/pq` driver, I would be fine with that.

**Comment by travelliu** [comment]
@kenshaw the driver is not lib/pq. Different password authentication protocols

**Comment by kenshaw** [comment]
This should not be a fork then; they should submit a PR upstream to `lib/pq`. I'm not interested in including this database driver.

**Comment by travelliu** [comment]
> The sha256 encryption authentication method of the database is different from that of PostgreSQL

**Comment by travelliu** [comment]
Do not add schema. usql can not add database driver

**Pull request closed without merging**
