### PR TITLE
feat: adding support for Databend

### PR DESCRIPTION
**Pull request by everpcpc**
ref:
* https://databend.rs/
* https://github.com/datafuselabs/databend

### CODE REVIEW

**Comment by kenshaw** [comment]
Some statements/questions:
1. Your company name is misspelled on this page on the upper right logo/header: https://docs.databend.com/develop/golang
2. The documentation seems to indicate that the way to use Databend previously was with the Clickhouse driver. It's worth noting that `dburl` already supports the Clickhouse driver, as does its sister project, `usql`

**Comment by everpcpc** [comment]
1. Thanks for pointing out the mistake!
2. We only support clickhouse http protocol, and the `databend-go` driver will work for both the opensource [databend](https://databend.rs/) and the [Databend Cloud](http://app.databend.com/) which needs some native features, such as upload to stage, similar to snowflake.

**Comment by kenshaw** [comment]
I'm happy to merge this, assuming you're also going to be adding a `usql` driver. If you want the DSN syntax to be `databend+<xyz>` -- that's kind of your call -- but I'd highly suggest modeling it around how PostgreSQL and others do it, with a query parameter (ie `?sslmode=disable`). The issue with `http` is that is _entirely_ a different protocol. I have no idea if Databend actually communicates using HTTP, but this is what would be called an "encapsulated" or a "layered" protocol. All conventions for protocols are to define that in the top level. For example, using something like `databend` and `databends` or doing `databend://?sslmode=disable`.

**Comment by everpcpc** [comment]
I've changed the scheme to use argument `sslmode`, and I would start working on `usql` driver then.

**Comment by kenshaw** [comment]
Two things: I do not want to adopt `db` as the short for this database (nor for any other). It's too close to typos that people might use, and will cause greater issues/confusion. Separately, please rebase into a single commit.

**Comment by kenshaw** [comment]
Reviewing the current aliases, since there are no other drivers that begin with the letter `d` yet, I'll accept for the short alias any of the following:

`da`, `de`, `dd`, or any other `d*` except for `db`. 

Additionally, there's no limit on other aliases you could add, as long as they don't conflict with other aliases and match the database driver. I'd suggest adding `dbd`, `bend` and `dd` as aliases.

**Comment by everpcpc** [comment]
Hi, I changed the alias to `bend` and rebased commits.

**Pull request merged**
