### PR TITLE
Add IBM Netezza

### PR DESCRIPTION
**Pull request by nineinchnick**

### CODE REVIEW

**Comment by kenshaw** [comment]
@nineinchnick if this is a wire compatible with PostgreSQL, it doesn't need its own scheme definition, but instead just have an alias added.

**Comment by nineinchnick** [comment]
I don't think they are wire compatible. `psql` doesn't work:
```
% psql -h 127.0.0.1 -p 5580 -d test -U admin     
psql: error: Invalid - opcode
Invalid - opcode
```

They forked from PostgreSQL 7, somewhere in 2001.

Anyway, I've been testing their native Go driver and found some major issues, like https://github.com/IBM/nzgo/issues/23. I can keep this open for a while until I test that driver a bit more (and see if authors can actually address any issues).

**Comment by nineinchnick** [comment]
Queries with bound params don't work (so `\dt` doesn't) but everything typed into `usql` is a plain query and works fine. As there's no other publicly available Netezza client (getting the JDBC driver and/or standalone client requires logging in to IBM), I'd say this is valuable to have.

**Comment by nineinchnick** [comment]
BTW I don't have write access in this repo.

**Comment by kenshaw** [comment]
@nineinchnick Sorry, I didn't realize I had to set default 'member privileges' on the organization. I had manually added you as a member to the individual repos previously. Please check now and let me know.

**Pull request merged**
